### ISSUE TITLE
How to set the line-height?

### ISSUE THREAD

**Issue by hkongm** [MiguelCastillo/Brackets-Themes#48]
There is setting in new version, that's awesome!
But the line height is weird when I change the default font-size in setting.
How do I change the line-height? 
Or you can set both of font-size and line-height in font.
Like font:18px/1.5em arial
Thanks.

**Comment by jesuscmd** [comment]
English: Hi!!! It's true, its so easy, its like configure a text in web, i writed these settings in brackets.min.css, the zoom is quite ugly and hard to read, in order to resolve it, I set two styles properties: *font-weight: 100!important;* and *line-height:1.6*, this makes clear and easy to read!!!!

Español: Hola, el zoom de Brackets es muy malo, para resolverlo edité el archivo brackets.min.css, y edité .CodeMirror en la carpeta www/styles con los siguientes estilos, la clave es el peso de la fuente *font-weight: 100!important;*:
```
.CodeMirror {
line-height:1.6;
 font-family:"SourceCodePro-Medium","ＭＳ ゴシック","MS Gothic",monospace;//like sublime text
 font-weight: 100!important; //this make the text clear and easy to read!
}
```

These are the results:

![screen-shot-2015-10-30-at-12 09 38-pm](https://cloud.githubusercontent.com/assets/4097436/10854354/cc5811c2-7f00-11e5-9551-77e842ba0ee2.jpg)

This is easier to read than the brackets zoom default:
![feo](https://cloud.githubusercontent.com/assets/4097436/10854356/d2b80da6-7f00-11e5-9019-377735fdd46d.jpg)

**Comment by MiguelCastillo** [comment]
@jesuscmd Yup, I saw that in the Brackets post.  I will post back in that thread.  BTW, it would be easier if you had referenced this issue in the other thread instead of copying the content of the message.  That helps because you can navigate between both conversations by clicking on a link :)

**Comment by montagnez** [comment]
Resolve the  problem : 

1 -  go to :  AppData\Roaming\Brackets\extensions\user\FolderExtention

2 - Go to newtondark.css for example for me.

3 - add this line : 

.CodeMirror {
    line-height: 1.6;
}

4 - Be happy !

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/Brackets-LineStyle
